#pragma once
#include <pgmspace.h>
const char kEmbeddedIndexPage[] PROGMEM =
  "<!DOCTYPE html>\n"
  "<html lang=\"zh\" data-theme=\"dark\">\n"
  "<head>\n"
  "<meta charset=\"UTF-8\">\n"
  "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,user-scalable=no\">\n"
  "<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\n"
  "<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\">\n"
  "<meta name=\"apple-mobile-web-app-title\" content=\"CarKey\">\n"
  "<meta name=\"mobile-web-app-capable\" content=\"yes\">\n"
  "<meta name=\"theme-color\" content=\"#060B14\">\n"
  "<link rel=\"manifest\" href=\"/manifest.json\">\n"
  "<title>CarKey V6</title>\n"
  "<style>\n"
  ":root{\n"
  "--bg:#060B14;--card:#101827;--border:#1D2A44;--accent:#00D4FF;--green:#00FF99;\n"
  "--warn:#FFB347;--red:#FF5F56;--txt:#FFFFFF;--sub:#8B98B8;\n"
  "--glow-accent:rgba(0,212,255,0.25);--glow-green:rgba(0,255,153,0.3);\n"
  "--glow-red:rgba(255,95,86,0.25);--radius:20px;--radius-sm:12px;\n"
  "--glass-bg:rgba(16,24,39,0.7);--glass-border:rgba(255,255,255,0.05);--glass-shadow:0 8px 32px rgba(0,0,0,0.4);\n"
  "--toast-bg:rgba(16,24,39,0.95);\n"
  "}\n"
  "[data-theme=\"light\"]{\n"
  "--bg:#F0F2F5;--card:#FFFFFF;--border:#D1D5DB;--accent:#0099CC;--green:#00AA55;\n"
  "--warn:#E69500;--red:#DD3333;--txt:#1A1A2E;--sub:#6B7280;\n"
  "--glow-accent:rgba(0,153,204,0.2);--glow-green:rgba(0,170,85,0.2);\n"
  "--glow-red:rgba(221,51,51,0.2);\n"
  "--glass-bg:rgba(255,255,255,0.85);--glass-border:rgba(0,0,0,0.08);--glass-shadow:0 4px 24px rgba(0,0,0,0.08);\n"
  "--toast-bg:rgba(255,255,255,0.95);\n"
  "}\n"
  "*{box-sizing:border-box;-webkit-tap-highlight-color:transparent;margin:0;padding:0}\n"
  "body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;background:var(--bg);color:var(--txt);transition:background 0.4s,color 0.4s;\n"
  "min-height:100vh;max-width:480px;margin:0 auto;padding:16px 14px 24px;overflow-x:hidden}\n"
  "\n"
  ".glass{background:var(--glass-bg);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);\n"
  "border:1px solid var(--glass-border);box-shadow:var(--glass-shadow);border-radius:var(--radius)}\n"
  "\n"
  ".header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}\n"
  ".logo{font-size:20px;font-weight:800;letter-spacing:3px;background:linear-gradient(135deg,var(--accent),#0099CC);\n"
  "-webkit-background-clip:text;-webkit-text-fill-color:transparent}\n"
  ".logo span{font-size:11px;font-weight:400;opacity:0.5}\n"
  ".settings-btn{width:36px;height:36px;border-radius:50%;background:rgba(255,255,255,0.04);\n"
  "border:1px solid rgba(255,255,255,0.08);color:var(--sub);font-size:18px;cursor:pointer;\n"
  "display:flex;align-items:center;justify-content:center;transition:all 0.3s}\n"
  ".settings-btn:active{background:rgba(0,212,255,0.15);color:var(--accent);transform:scale(0.92)}\n"
  "\n"
  ".capsules{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:20px}\n"
  "[data-theme=\"light\"] .capsule{background:rgba(0,0,0,0.04);border-color:rgba(0,0,0,0.1)}\n"
  ".capsule{display:flex;align-items:center;gap:5px;padding:6px 12px;border-radius:20px;font-size:11px;\n"
  "font-weight:600;border:1px solid rgba(255,255,255,0.08);background:rgba(16,24,39,0.5);color:var(--sub);transition:all 0.4s}\n"
  ".capsule .dot{width:6px;height:6px;border-radius:50%;background:currentColor;flex-shrink:0}\n"
  ".capsule.on{border-color:rgba(0,255,153,0.3);color:var(--green)}.capsule.on .dot{box-shadow:0 0 6px var(--green)}\n"
  ".capsule.warn{border-color:rgba(255,179,71,0.3);color:var(--warn)}.capsule.warn .dot{box-shadow:0 0 6px var(--warn)}\n"
  ".capsule.off{border-color:rgba(255,255,255,0.05);color:var(--sub)}\n"
  "\n"
  ".engine-hero{display:flex;flex-direction:column;align-items:center;margin:10px 0 24px}\n"
  ".engine-ring{width:180px;height:180px;border-radius:50%;display:flex;align-items:center;justify-content:center;\n"
  "cursor:pointer;border:3px solid rgba(255,255,255,0.08);transition:all 0.6s cubic-bezier(0.4,0,0.2,1);position:relative}\n"
  ".engine-ring::before{content:'';position:absolute;inset:-8px;border-radius:50%;border:2px solid transparent;transition:all 0.6s}\n"
  ".engine-ring.running{border-color:rgba(0,255,153,0.5);box-shadow:0 0 60px var(--glow-green),inset 0 0 40px rgba(0,255,153,0.05)}\n"
  ".engine-ring.running::before{border-color:rgba(0,255,153,0.15);animation:ring-pulse 2.5s ease-in-out infinite}\n"
  ".engine-ring.stopped{border-color:rgba(255,95,86,0.3);box-shadow:0 0 30px rgba(255,95,86,0.1)}\n"
  ".engine-ring.starting{border-color:rgba(0,212,255,0.5);box-shadow:0 0 50px var(--glow-accent)}\n"
  ".engine-ring.starting::before{border-color:rgba(0,212,255,0.2);animation:ring-spin 1.5s linear infinite}\n"
  "@keyframes ring-pulse{0%,100%{transform:scale(1);opacity:0.3}50%{transform:scale(1.04);opacity:0.7}}\n"
  "@keyframes ring-spin{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}\n"
  ".engine-inner{display:flex;flex-direction:column;align-items:center;z-index:1}\n"
  ".engine-icon{font-size:40px;margin-bottom:4px;transition:transform 0.5s}\n"
  ".engine-ring.running .engine-icon{animation:icon-breathe 2s ease-in-out infinite}\n"
  "@keyframes icon-breathe{0%,100%{transform:scale(1)}50%{transform:scale(1.12)}}\n"
  ".engine-label{font-size:11px;letter-spacing:3px;color:var(--sub);margin-bottom:2px}\n"
  ".engine-state{font-size:16px;font-weight:800;letter-spacing:2px;transition:color 0.5s}\n"
  ".engine-ring.running .engine-state{color:var(--green)}\n"
  ".engine-ring.stopped .engine-state{color:var(--red)}\n"
  ".engine-ring.starting .engine-state{color:var(--accent)}\n"
  ".engine-btn-wrap{margin-top:16px}\n"
  ".engine-btn{width:140px;height:44px;border-radius:22px;border:none;font-size:14px;font-weight:700;\n"
  "letter-spacing:2px;cursor:pointer;transition:all 0.3s;text-transform:uppercase}\n"
  ".engine-btn.start{background:linear-gradient(135deg,var(--accent),#0099CC);color:#060B14;box-shadow:0 4px 20px var(--glow-accent)}\n"
  ".engine-btn.start:active{transform:scale(0.94)}\n"
  ".engine-btn.stop{background:linear-gradient(135deg,var(--red),#cc4444);color:#fff;box-shadow:0 4px 20px var(--glow-red)}\n"
  ".engine-btn.stop:active{transform:scale(0.94)}\n"
  "\n"
  ".status-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:16px}\n"
  ".status-card{padding:16px 14px;display:flex;align-items:center;gap:12px;\n"
  "background:rgba(16,24,39,0.7);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);\n"
  "border:1px solid rgba(255,255,255,0.05);border-radius:var(--radius-sm);transition:all 0.4s}\n"
  ".status-card .sc-icon{font-size:24px;width:36px;text-align:center;flex-shrink:0;transition:all 0.4s}\n"
  ".status-card .sc-info{display:flex;flex-direction:column;gap:2px;min-width:0}\n"
  ".status-card .sc-val{font-size:14px;font-weight:700}\n"
  ".status-card .sc-sub{font-size:10px;color:var(--sub)}\n"
  ".status-card.on{border-color:rgba(0,255,153,0.2);box-shadow:0 0 20px rgba(0,255,153,0.05)}\n"
  ".status-card.on .sc-val{color:var(--green)}.status-card.on .sc-icon{filter:drop-shadow(0 0 8px var(--glow-green))}\n"
  ".status-card.off{border-color:rgba(255,95,86,0.15)}.status-card.off .sc-val{color:var(--red)}\n"
  ".status-card.warn-card{border-color:rgba(255,179,71,0.2)}.status-card.warn-card .sc-val{color:var(--warn)}\n"
  "\n"
  ".actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:16px}\n"
  ".action-btn{display:flex;flex-direction:column;align-items:center;gap:8px;padding:18px 12px;\n"
  "background:rgba(16,24,39,0.7);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);\n"
  "border:1px solid rgba(255,255,255,0.05);border-radius:var(--radius-sm);cursor:pointer;\n"
  "transition:all 0.3s;color:var(--txt)}\n"
  ".action-btn .act-icon{font-size:28px;transition:transform 0.3s}\n"
  ".action-btn .act-label{font-size:12px;font-weight:600;letter-spacing:1px}\n"
  ".action-btn:active{transform:scale(0.94);background:rgba(0,212,255,0.08);border-color:rgba(0,212,255,0.2)}\n"
  ".action-btn:active .act-icon{transform:scale(1.15)}\n"
  "\n"
  ".events{margin-bottom:16px}\n"
  ".events-header{font-size:10px;letter-spacing:3px;color:var(--sub);margin-bottom:8px;font-weight:600}\n"
  ".events-panel{padding:12px 14px}.event-item{display:flex;gap:10px;padding:5px 0;font-size:11px;\n"
  "align-items:flex-start;border-bottom:1px solid rgba(255,255,255,0.03)}\n"
  ".event-item:last-child{border-bottom:none}.event-time{color:var(--sub);white-space:nowrap;flex-shrink:0}\n"
  ".event-msg.ok{color:var(--green)}.event-msg.warn{color:var(--warn)}.event-msg.err{color:var(--red)}\n"
  ".vehicle-svg-wrap{display:flex;justify-content:center;margin:0 0 16px}\n"
  "#vehicleSvg{max-width:100%;height:auto;display:block}\n"
  "#vehicleSvg svg{display:block;max-width:100%;height:auto}.event-msg.info{color:var(--sub)}\n"
  "\n"
  ".overlay{position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(6,11,20,0.96);\n"
  "display:none;justify-content:center;align-items:center;z-index:9999;backdrop-filter:blur(4px)}\n"
  ".modal-box{width:90%;max-width:360px;padding:24px 20px}\n"
  ".modal-title{font-size:15px;font-weight:700;margin-bottom:16px;display:flex;align-items:center;gap:8px}\n"
  "label{display:block;font-size:11px;color:var(--sub);margin:12px 0 4px;letter-spacing:0.5px}\n"
  "input,select{width:100%;padding:10px 12px;border-radius:10px;border:1px solid var(--border);\n"
  "background:rgba(0,0,0,0.4);color:var(--txt);font-size:13px;outline:none;transition:border 0.3s}\n"
  "[data-theme=\"light\"] input,[data-theme=\"light\"] select{background:rgba(0,0,0,0.04)}\n"
  "input:focus{border-color:var(--accent)}\n"
  ".btn-row{display:flex;gap:8px;margin-top:18px;justify-content:flex-end}\n"
  ".btn{padding:10px 20px;border-radius:10px;border:none;cursor:pointer;font-size:12px;font-weight:600;letter-spacing:0.5px;transition:all 0.3s}\n"
  ".btn-primary{background:var(--accent);color:#060B14}.btn-primary:active{opacity:0.8;transform:scale(0.96)}\n"
  ".btn-danger{background:var(--red);color:#fff}.btn-ghost{background:transparent;border:1px solid var(--border);color:var(--sub)}\n"
  ".toggle-row{display:flex;justify-content:space-between;align-items:center;padding:6px 0;font-size:12px}\n"
  ".toggle{position:relative;display:inline-block;width:44px;height:26px}.toggle input{display:none}\n"
  ".toggle .slider{position:absolute;cursor:pointer;top:0;left:0;right:0;bottom:0;\n"
  "background:rgba(139,152,184,0.2);border-radius:26px;transition:0.3s}\n"
  ".toggle .slider::before{content:'';position:absolute;height:20px;width:20px;left:3px;bottom:3px;\n"
  "background:#fff;border-radius:50%;transition:0.3s}\n"
  ".toggle input:checked+.slider{background:var(--accent)}.toggle input:checked+.slider::before{transform:translateX(18px)}\n"
  ".divider{height:1px;background:rgba(255,255,255,0.05);margin:12px 0}\n"
  ".ota-section{margin-top:4px}.ota-title{font-size:11px;color:var(--accent);font-weight:600;margin-bottom:8px}\n"
  ".ota-ver{font-size:10px;color:var(--sub);margin-bottom:8px}\n"
  ".ota-row{display:flex;gap:6px;align-items:center;margin-bottom:6px;flex-wrap:wrap}\n"
  ".ota-input{flex:1;min-width:100px;padding:7px 10px;border-radius:8px;border:1px solid var(--border);\n"
  "background:rgba(0,0,0,0.4);color:var(--txt);font-size:10px}\n"
  ".ota-btn{font-size:10px;padding:6px 12px;border-radius:8px;border:1px solid var(--border);\n"
  "background:transparent;color:var(--sub);cursor:pointer;white-space:nowrap;transition:0.2s}\n"
  ".ota-btn:active{background:rgba(0,212,255,0.1);color:var(--accent)}\n"
  ".ota-btn.primary{background:var(--accent);color:#060B14;border-color:var(--accent)}\n"
  ".ota-btn.danger{color:var(--red);border-color:var(--red)}\n"
  ".ota-progress-wrap{display:none;margin:6px 0}\n"
  ".ota-progress-bar{width:100%;height:6px;border-radius:3px;background:rgba(255,255,255,0.06);overflow:hidden}\n"
  ".ota-progress-fill{height:100%;width:0%;background:linear-gradient(90deg,var(--accent),#0099CC);transition:width 0.3s;border-radius:3px}\n"
  ".ota-progress-text{font-size:9px;color:var(--sub);margin-top:3px;text-align:center}\n"
  ".pair-status{font-size:10px;padding:3px 10px;border-radius:10px;font-weight:500}\n"
  ".badge-none{background:rgba(139,152,184,0.1);color:var(--sub)}\n"
  ".badge-ok{background:rgba(0,255,153,0.1);color:var(--green)}\n"
  ".badge-ing{background:rgba(0,212,255,0.1);color:var(--accent);animation:pulse 1.5s infinite}\n"
  "@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.4}}\n"
  ".fade-in{animation:fadeIn 0.5s ease-out}\n"
  "@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}\n"
  ".slide-up{animation:slideUp 0.4s ease-out}\n"
  "@keyframes slideUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}\n"
  "#authMsg{font-size:11px;color:var(--red);margin-top:6px;min-height:18px}\n"
  "#settingsMsg{font-size:11px;color:var(--red);margin-top:8px;min-height:18px}\n"
  ".toast-container{position:fixed;top:16px;left:50%;transform:translateX(-50%);z-index:9998;display:flex;flex-direction:column;gap:8px;pointer-events:none}\n"
  ".toast{padding:10px 20px;border-radius:12px;background:var(--toast-bg);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);\n"
  "border:1px solid var(--glass-border);box-shadow:var(--glass-shadow);font-size:12px;font-weight:600;\n"
  "animation:toastIn 0.4s ease-out,toastOut 0.3s 2.5s ease-in forwards;pointer-events:auto;white-space:nowrap}\n"
  ".toast.ok{border-left:3px solid var(--green)}.toast.warn{border-left:3px solid var(--warn)}.toast.err{border-left:3px solid var(--red)}\n"
  "@keyframes toastIn{from{opacity:0;transform:translateY(-20px)}to{opacity:1;transform:translateY(0)}}\n"
  "@keyframes toastOut{from{opacity:1}to{opacity:0;transform:translateY(-20px)}}\n"
  ".ws-indicator{width:8px;height:8px;border-radius:50%;background:var(--sub);transition:background 0.3s}\n"
  ".ws-indicator.live{background:var(--green);box-shadow:0 0 6px var(--green)}\n"
  "</style>\n"
  "</head>\n"
  "<body>\n"
  "<div class=\"toast-container\" id=\"toastContainer\"></div>\n"
  "<div class=\"header fade-in\"><div class=\"logo\">CARKEY <span>V6</span></div><div class=\"header-right\"><div class=\"ws-indicator\" id=\"wsDot\" title=\"WebSocket\"></div><div class=\"icon-btn\" id=\"themeBtn\" onclick=\"toggleTheme()\" title=\"Theme\">&#9788;</div><div class=\"settings-btn icon-btn\" onclick=\"openSettings()\">&#9881;</div></div></div>\n"
  "\n"
  "<div class=\"capsules slide-up\" id=\"capsules\">\n"
  "<div class=\"capsule\" id=\"capGear\"><span class=\"dot\"></span><span class=\"val\">--</span></div>\n"
  "<div class=\"capsule\" id=\"capBrake\"><span class=\"dot\"></span><span class=\"val\">Brake</span></div>\n"
  "<div class=\"capsule\" id=\"capBle\"><span class=\"dot\"></span><span class=\"val\">BLE</span></div>\n"
  "<div class=\"capsule\" id=\"capNfc\"><span class=\"dot\"></span><span class=\"val\">NFC</span></div>\n"
  "<div class=\"capsule\" id=\"capVolt\"><span class=\"dot\"></span><span class=\"val\">--.-V</span></div>\n"
  "</div>\n"
  "\n"
  "<div class=\"engine-hero fade-in\">\n"
  "<div class=\"engine-ring stopped\" id=\"engRing\" onclick=\"toggleEngine()\">\n"
  "<div class=\"engine-inner\"><div class=\"engine-icon\">&#9889;</div><div class=\"engine-label\">ENGINE</div><div class=\"engine-state\" id=\"engState\">STOPPED</div></div></div>\n"
  "<div class=\"engine-btn-wrap\"><button class=\"engine-btn start\" id=\"engBtn\" onclick=\"toggleEngine()\">START</button></div></div>\n"
  "\n"
  "<div class=\"status-grid slide-up\">\n"
  "<div class=\"status-card off\" id=\"scEngine\"><div class=\"sc-icon\">&#9889;</div><div class=\"sc-info\"><div class=\"sc-val\">STOPPED</div><div class=\"sc-sub\">Engine</div></div></div>\n"
  "<div class=\"status-card\" id=\"scBatt\"><div class=\"sc-icon\">&#9889;</div><div class=\"sc-info\"><div class=\"sc-val\" id=\"scBattV\">--.-V</div><div class=\"sc-sub\" id=\"scBattH\">Battery</div></div></div>\n"
  "<div class=\"status-card off\" id=\"scAcc\"><div class=\"sc-icon\">&#9889;</div><div class=\"sc-info\"><div class=\"sc-val\">OFF</div><div class=\"sc-sub\">ACC</div></div></div>\n"
  "<div class=\"status-card off\" id=\"scBrake\"><div class=\"sc-icon\">&#9888;</div><div class=\"sc-info\"><div class=\"sc-val\">RELEASED</div><div class=\"sc-sub\">Park Brake</div></div></div>\n"
  "<div class=\"status-card off\" id=\"scDoor\"><div class=\"sc-icon\">&#128682;</div><div class=\"sc-info\"><div class=\"sc-val\">CLOSED</div><div class=\"sc-sub\">Driver Door</div></div></div>\n"
  "</div>\n"
  "\n"
  "<div class=\"actions slide-up\">\n"
  "<div class=\"action-btn\" onclick=\"doApi('/api/unlock')\"><div class=\"act-icon\">&#128275;</div><div class=\"act-label\">Unlock</div></div>\n"
  "<div class=\"action-btn\" onclick=\"doApi('/api/lock')\"><div class=\"act-icon\">&#128274;</div><div class=\"act-label\">Lock</div></div>\n"
  "<div class=\"action-btn\" onclick=\"doApi('/api/horn')\"><div class=\"act-icon\">&#128226;</div><div class=\"act-label\">Horn</div></div>\n"
  "<div class=\"action-btn\" onclick=\"doApi('/api/window')\"><div class=\"act-icon\">&#9644;</div><div class=\"act-label\">Window</div></div>\n"
  "</div>\n"
  "\n"
  "<div class=\"vehicle-svg-wrap slide-up\" id=\"vehicleSvgWrap\"><div id=\"vehicleSvg\"></div></div>\n"
  "\n"
  "<div class=\"events slide-up\"><div class=\"events-header\">SYSTEM EVENTS</div><div class=\"events-panel glass\" id=\"eventsList\"></div></div>\n"
  "\n"
  "<div class=\"overlay\" id=\"authOverlay\"><div class=\"modal-box glass\">\n"
  "<div class=\"modal-title\"><span>&#128272;</span><span id=\"authModalTitle\">Start Engine</span></div>\n"
  "<input type=\"password\" id=\"authPwd\" placeholder=\"Enter 6-digit PIN\" maxlength=\"6\" inputmode=\"numeric\" autocomplete=\"off\">\n"
  "<div id=\"authMsg\"></div><div class=\"btn-row\">\n"
  "<button class=\"btn btn-ghost\" onclick=\"closeAuth()\">Cancel</button>\n"
  "<button class=\"btn btn-primary\" onclick=\"doStart()\">Confirm</button>\n"
  "</div></div></div>\n"
  "\n"
  "<div class=\"overlay\" id=\"settingsOverlay\"><div class=\"modal-box glass\">\n"
  "<div class=\"modal-title\"><span>&#9881;</span>Settings</div>\n"
  "<label>WiFi SSID</label><input type=\"text\" id=\"cfgSsid\" placeholder=\"WiFi name\">\n"
  "<label>WiFi Password</label><input type=\"password\" id=\"cfgPass\" placeholder=\"WiFi password\">\n"
  "<label>Bluetooth Name</label><input type=\"text\" id=\"cfgBt\" placeholder=\"Device name\">\n"
  "<label>Start PIN</label><input type=\"password\" id=\"cfgPwd\" placeholder=\"6-digit PIN\">\n"
  "<div class=\"toggle-row\"><span>Security Auth</span><label class=\"toggle\"><input type=\"checkbox\" id=\"cfgSec\"><span class=\"slider\"></span></label></div>\n"
  "<div class=\"toggle-row\"><span>BLE Scan</span><label class=\"toggle\"><input type=\"checkbox\" id=\"cfgBleScan\"><span class=\"slider\"></span></label></div>\n"
  "<div class=\"toggle-row\"><span>NFC Scan</span><label class=\"toggle\"><input type=\"checkbox\" id=\"cfgNfcScan\"><span class=\"slider\"></span></label></div>\n"
  "<div class=\"divider\"></div>\n"
  "<div style=\"font-size:11px;color:var(--accent);font-weight:600;margin-bottom:6px\">&#128225; BLE Pairing</div>\n"
  "<div id=\"pInfo\" style=\"font-size:10px;color:var(--sub);margin:4px 0\">Tap start and search on phone</div>\n"
  "<div style=\"display:flex;gap:6px;align-items:center\">\n"
  "<button class=\"ota-btn\" id=\"pStart\" onclick=\"startPair()\">Start</button>\n"
  "<button class=\"ota-btn\" id=\"pStop\" onclick=\"stopPair()\" style=\"display:none\">Stop</button>\n"
  "<button class=\"ota-btn danger\" onclick=\"clearPair()\">Clear</button>\n"
  "<span class=\"pair-status badge-none\" id=\"pBadge\">None</span></div>\n"
  "<div class=\"divider\"></div>\n"
  "<div class=\"ota-section\">\n"
  "<div class=\"ota-title\">&#128190; OTA Update</div><div class=\"ota-ver\" id=\"otaVer\">Version: --</div>\n"
  "<div class=\"ota-row\"><button class=\"ota-btn primary\" id=\"otaUploadBtn\" onclick=\"startOtaUpload()\">Upload .bin</button>\n"
  "<input type=\"file\" id=\"otaFileInput\" accept=\".bin\" style=\"display:none\" onchange=\"handleOtaFile()\"></div>\n"
  "<div class=\"ota-row\"><input type=\"text\" class=\"ota-input\" id=\"otaUrl\" placeholder=\"Or paste firmware URL...\">\n"
  "<button class=\"ota-btn\" onclick=\"startOtaDownload()\">Download</button></div>\n"
  "<div class=\"ota-progress-wrap\" id=\"otaProgressWrap\"><div class=\"ota-progress-bar\"><div class=\"ota-progress-fill\" id=\"otaProgressFill\"></div></div><div class=\"ota-progress-text\" id=\"otaProgressText\">0%</div></div>\n"
  "<div class=\"ota-row\"><button class=\"ota-btn danger\" id=\"otaRollbackBtn\" style=\"display:none\" onclick=\"doRollback()\">Rollback</button></div></div>\n"
  "<div class=\"divider\"></div>\n"
  "<div class=\"btn-row\"><button class=\"btn btn-ghost\" onclick=\"closeSettings()\">Cancel</button>\n"
  "<button class=\"btn btn-danger\" onclick=\"rebootDevice()\">Reboot</button>\n"
  "<button class=\"btn btn-primary\" onclick=\"saveSettings()\">Save</button></div>\n"
  "<div id=\"settingsMsg\"></div></div></div>\n"
  "\n"
  "<script>\n"
  "var E=function(id){return document.getElementById(id)};\n"
  "var _ws=null,_wsConnected=false,_prevDoor=null,_prevEngine=null,_prevAcc=null,_prevBrake=null;\n"
  "function toggleTheme(){var h=document.documentElement;var t=h.getAttribute(\"data-theme\")===\"dark\"?\"light\":\"dark\";h.setAttribute(\"data-theme\",t);localStorage.setItem(\"carkey-theme\",t);E(\"themeBtn\").innerHTML=t===\"dark\"?\"&#9788;\":\"&#9790;\";toast(\"Theme: \"+t.toUpperCase(),\"info\")}\n"
  "(function(){var t=localStorage.getItem(\"carkey-theme\")||\"dark\";document.documentElement.setAttribute(\"data-theme\",t);setTimeout(function(){E(\"themeBtn\").innerHTML=t===\"dark\"?\"&#9788;\":\"&#9790;\"},100)})()\n"
  "function toast(m,c){var ct=E(\"toastContainer\");var el=document.createElement(\"div\");el.className=\"toast \"+(c||\"info\");el.innerHTML=m;ct.appendChild(el);setTimeout(function(){el.remove()},3000)}\n"
  "function connectWS(){if(_ws&&_ws.readyState===WebSocket.OPEN)return;var proto=location.protocol===\"https:\"?\"wss\":\"ws\";var url=proto+\"://\"+location.hostname+\":81/\";try{_ws=new WebSocket(url)}catch(e){_ws=null;return}_ws.onopen=function(){_wsConnected=true;E(\"wsDot\").className=\"ws-indicator live\"};_ws.onclose=function(){_wsConnected=false;E(\"wsDot\").className=\"ws-indicator\";_ws=null;setTimeout(connectWS,5000)};_ws.onerror=function(){_ws.close()};_ws.onmessage=function(e){try{var d=JSON.parse(e.data);applyStatus(d)}catch(ex){}}}\n"
  "function renderVehicleSvg(engine,battV,battH,acc,brake,door){var w=320,h=140;var bc=battH===\"GOOD\"?\"var(--green)\":battH===\"LOW\"||battH===\"BAT_LOW\"?\"var(--warn)\":\"var(--red)\";var s=\"<svg viewBox=\\'0 0 \"+w+\" \"+h+\"\\' xmlns=\\'http://www.w3.org/2000/svg\\'>\";s+=\"<rect x=\\'40\\' y=\\'30\\' width=\\'240\\' height=\\'70\\' rx=\\'12\\' fill=\\'none\\' stroke=\\'var(--sub)\\' stroke-width=\\'2\\' opacity=\\'0.5\\'/>\";s+=\"<rect x=\\'55\\' y=\\'40\\' width=\\'50\\' height=\\'50\\' rx=\\'6\\' fill=\\'none\\' stroke=\\'var(--sub)\\' stroke-width=\\'1.5\\' opacity=\\'0.4\\'/>\";s+=\"<rect x=\\'215\\' y=\\'40\\' width=\\'50\\' height=\\'50\\' rx=\\'6\\' fill=\\'none\\' stroke=\\'var(--sub)\\' stroke-width=\\'1.5\\' opacity=\\'0.4\\'/>\";s+=\"<circle cx=\\'160\\' cy=\\'65\\' r=\\'18\\' fill=\\'none\\' stroke=\\'\"+bc+\"\\' stroke-width=\\'2.5\\'/>\";s+=\"<text x=\\'160\\' y=\\'69\\' text-anchor=\\'middle\\' font-size=\\'10\\' fill=\\'var(--txt)\\'>\"+(battV?battV.toFixed(1)+\"V\":\"--\")+\"</text>\";s+=\"<rect x=\\'140\\' y=\\'40\\' width=\\'40\\' height=\\'24\\' rx=\\'4\\' fill=\\'\"+(engine?\"var(--green)\":\"var(--sub)\")+\"\\' opacity=\\'\"+(engine?\"0.6\":\"0.3\")+\"\\' stroke=\\'var(--sub)\\' stroke-width=\\'1.5\\'/>\";s+=\"<text x=\\'160\\' y=\\'56\\' text-anchor=\\'middle\\' font-size=\\'8\\' fill=\\'var(--txt)\\'>ENG</text>\";s+=\"<text x=\\'160\\' y=\\'105\\' text-anchor=\\'middle\\' font-size=\\'9\\' fill=\\'var(--sub)\\'>\"+battH+\"</text>\";if(door){s+=\"<rect x=\\'55\\' y=\\'40\\' width=\\'50\\' height=\\'50\\' rx=\\'6\\' fill=\\'var(--red)\\' opacity=\\'0.3\\' stroke=\\'var(--red)\\' stroke-width=\\'2\\'><animate attributeName=\\'opacity\\' values=\\'0.3;0.7;0.3\\' dur=\\'1s\\' repeatCount=\\'indefinite\\'/></rect>\"}if(brake){s+=\"<text x=\\'100\\' y=\\'80\\' font-size=\\'9\\' fill=\\'var(--green)\\'>P</text>\"}if(acc){s+=\"<text x=\\'200\\' y=\\'80\\' font-size=\\'9\\' fill=\\'var(--accent)\\'>ACC ON</text>\"}s+=\"<text x=\\'60\\' y=\\'125\\' font-size=\\'8\\' fill=\\'\"+bc+\"\\'>BAT</text><text x=\\'110\\' y=\\'125\\' font-size=\\'8\\' fill=\\'var(--sub)\\'>BRK</text><text x=\\'160\\' y=\\'125\\' font-size=\\'8\\' fill=\\'var(--sub)\\'>ENG</text><text x=\\'210\\' y=\\'125\\' font-size=\\'8\\' fill=\\'var(--sub)\\'>ACC</text><text x=\\'260\\' y=\\'125\\' font-size=\\'8\\' fill=\\'var(--sub)\\'>DR</text>\";s+=\"</svg>\";E(\"vehicleSvg\").innerHTML=s}\n"
  "var E=function(id){return document.getElementById(id)};\n"
  "var _lastEngine=null,_lastLocked=null,_events=[];\n"
  "\n"
  "function addLog(m,t){var d=new Date(),ts=('0'+d.getHours()).slice(-2)+':'+('0'+d.getMinutes()).slice(-2)+':'+('0'+d.getSeconds()).slice(-2);_events.unshift({t:ts,m:m,c:t||'info'});if(_events.length>20)_events.pop();renderEvents()}\n"
  "function renderEvents(){var h='';for(var i=0;i<Math.min(_events.length,5);i++){var e=_events[i];h+='<div class=\"event-item slide-up\"><span class=\"event-time\">'+e.t+'</span><span class=\"event-msg '+e.c+'\">'+e.m+'</span></div>'}E('eventsList').innerHTML=h}\n"
  "addLog('System Ready','ok');\n"
  "\n"
  "function toggleEngine(){var rn=E('engRing').classList.contains('running');if(rn){if(confirm('Stop engine?')){openAuth('stop')}}else{openAuth('start')}}\n"
  "function openAuth(m){window._authMode=m||'start';E('authOverlay').style.display='flex';E('authPwd').focus();E('authModalTitle').innerHTML=m==='stop'?'Stop Engine':'Start Engine'}\n"
  "function closeAuth(){E('authOverlay').style.display='none';E('authPwd').value='';E('authMsg').innerHTML=''}\n"
  "function doStart(){var p=E('authPwd').value;if(!p||p.length!==6){E('authMsg').innerHTML='Enter 6-digit PIN';return}var mode=window._authMode||'start';var url=mode==='stop'?'/api/stop_engine?pwd='+p:'/api/start_engine?pwd='+p;var label=mode==='stop'?'Engine Stop':'Engine Start';addLog(label+'...','info');if(mode==='start'){E('engRing').className='engine-ring starting';E('engState').innerHTML='STARTING'}fetch(url).then(function(r){if(r.status===200||r.status===202){addLog(label+' OK','ok');toast(label+' OK','ok');if(mode==='start'){E('engRing').className='engine-ring running';E('engState').innerHTML='RUNNING'}else{E('engRing').className='engine-ring stopped';E('engState').innerHTML='STOPPED';E('engBtn').className='engine-btn start';E('engBtn').innerHTML='START'}closeAuth();return}if(mode==='start'){E('engRing').className='engine-ring stopped';E('engState').innerHTML='STOPPED'}return r.text().then(function(t){if(r.status===401)E('authMsg').innerHTML='Wrong PIN';else if(r.status===409)E('authMsg').innerHTML='Engine not running';else if(r.status===503)E('authMsg').innerHTML=t||'Start failed';addLog(label+' Failed','err')})}).catch(function(){addLog('Network error','err')})}\n"
  "function doApi(url){addLog('Action: '+url.split('/').pop(),'info');fetch(url).then(function(r){return r.text()}).then(function(t){addLog('OK: '+t,'ok');toast('Action completed','ok')}).catch(function(){addLog('Failed','err')})}\n"
  "\n"
  "function applyStatus(d){\n"
  "var rn=d.engineRunning!==undefined?d.engineRunning:(d.engine_running||false);\n"
  "if(_prevEngine!==null&&_prevEngine!==rn){toast(rn?\"Engine Started\":\"Engine Stopped\",rn?\"ok\":\"info\")}_prevEngine=rn;\n"
  "if(_lastEngine!==null&&_lastEngine!==rn){addLog(rn?\"Engine started\":\"Engine stopped\",rn?\"ok\":\"info\")}_lastEngine=rn;\n"
  "if(rn){E(\"engRing\").className=\"engine-ring running\";E(\"engState\").innerHTML=\"RUNNING\";E(\"engBtn\").className=\"engine-btn stop\";E(\"engBtn\").innerHTML=\"STOP\"}\n"
  "else{E(\"engRing\").className=\"engine-ring stopped\";E(\"engState\").innerHTML=\"STOPPED\";E(\"engBtn\").className=\"engine-btn start\";E(\"engBtn\").innerHTML=\"START\"}\n"
  "var v=d.voltage||d.batteryVoltage||0;E(\"capVolt\").querySelector(\".val\").innerHTML=v?v.toFixed(1)+\"V\":\"--.-V\";E(\"capVolt\").className=\"capsule\"+(v<12?\" warn\":\" on\");\n"
  "var g=d.gear||\"--\";var gc=E(\"capGear\");gc.querySelector(\".val\").innerHTML=g;gc.className=\"capsule\"+(g===\"N\"?\" on\":\"\");\n"
  "var hb=d.handbrake!==undefined?d.handbrake:(d.handBrake||false);var bc=E(\"capBrake\");bc.querySelector(\".val\").innerHTML=hb?\"Brake ON\":\"Brake OFF\";bc.className=\"capsule\"+(hb?\" on\":\" off\");\n"
  "if(_prevBrake!==null&&_prevBrake!==hb){toast(hb?\"Hand Brake Engaged\":\"Hand Brake Released\",hb?\"warn\":\"info\")}_prevBrake=hb;\n"
  "var blc=E(\"capBle\");if(d.ble_scan===false){blc.querySelector(\".val\").innerHTML=\"BLE OFF\";blc.className=\"capsule off\"}else if(d.ble_authorized||d.ble_auth_valid){blc.querySelector(\".val\").innerHTML=\"BLE OK\";blc.className=\"capsule on\"}else if(d.ble_scanning){blc.querySelector(\".val\").innerHTML=\"Scanning\";blc.className=\"capsule on\"}else if(d.ble_last_seen>0){blc.querySelector(\".val\").innerHTML=d.ble_last_seen+\"s ago\";blc.className=\"capsule off\"}else{blc.querySelector(\".val\").innerHTML=\"Idle\";blc.className=\"capsule off\"}\n"
  "var nc=E(\"capNfc\");if(d.nfc_scan===false){nc.querySelector(\".val\").innerHTML=\"NFC OFF\";nc.className=\"capsule off\"}else if(d.config_locked){nc.querySelector(\".val\").innerHTML=\"Locked\";nc.className=\"capsule warn\"}else{nc.querySelector(\".val\").innerHTML=\"Ready\";nc.className=\"capsule on\"}\n"
  "var cl=d.config_locked;if(_lastLocked!==null&&_lastLocked!==cl){addLog(cl?\"Config locked\":\"Config unlocked\",cl?\"warn\":\"ok\")}_lastLocked=cl;\n"
  "var er=d.engineRunning||false;var se=E(\"scEngine\");se.querySelector(\".sc-val\").innerHTML=er?\"RUNNING\":\"STOPPED\";se.className=\"status-card\"+(er?\" on\":\" off\");\n"
  "var bv=d.batteryVoltage||0;var bh=d.batteryHealth;if(!bh){var v2=d.batteryVoltage||d.voltage||0;if(v2>=12.5)bh=\"GOOD\";else if(v2>=12.2)bh=\"LOW\";else if(v2>0)bh=\"CRITICAL\";else{var lb=d.low_battery;bh=lb===true?\"LOW\":lb===false?\"GOOD\":\"--\"}}E(\"scBattV\").innerHTML=bv?bv.toFixed(1)+\"V\":\"--.-V\";E(\"scBattH\").innerHTML=bh;\n"
  "var sb=E(\"scBatt\");if(bh===\"GOOD\")sb.className=\"status-card on\";else if(bh===\"LOW\"||bh===\"BAT_LOW\")sb.className=\"status-card warn-card\";else sb.className=\"status-card off\";\n"
  "var ac=d.acc||false;var sa=E(\"scAcc\");sa.querySelector(\".sc-val\").innerHTML=ac?\"ON\":\"OFF\";sa.className=\"status-card\"+(ac?\" on\":\" off\");\n"
  "if(_prevAcc!==null&&_prevAcc!==ac){toast(ac?\"ACC ON\":\"ACC OFF\",ac?\"info\":\"info\")}_prevAcc=ac;\n"
  "var hb2=d.handBrake!==undefined?d.handBrake:(d.handbrake||false);var sbr=E(\"scBrake\");sbr.querySelector(\".sc-val\").innerHTML=hb2?\"ENGAGED\":\"RELEASED\";sbr.className=\"status-card\"+(hb2?\" on\":\" off\");\n"
  "var dor=d.driverDoorOpen||false;var sd=E(\"scDoor\");sd.querySelector(\".sc-val\").innerHTML=dor?\"OPEN\":\"CLOSED\";sd.className=\"status-card\"+(dor?\" on\":\" off\");\n"
  "if(_prevDoor!==null&&_prevDoor!==dor){toast(dor?\"Driver Door Opened\":\"Driver Door Closed\",dor?\"err\":\"ok\")}_prevDoor=dor;\n"
  "renderVehicleSvg(er,bv,bh,ac,hb2,dor);}\n"
  "function fallbackPoll(){fetch(\"/api/status\").then(function(r){return r.json()}).then(function(d){applyStatus(d)}).catch(function(){})}\n"
  "function updateStatus(){fallbackPoll()}\n"
  "\n"
  "function updatePairStatus(){fetch('/api/ble/pairing/status').then(function(r){return r.json()}).then(function(d){\n"
  "if(d.pairing){E('pBadge').className='pair-status badge-ing';E('pBadge').innerHTML='Pairing...';E('pInfo').innerHTML='Search on phone Bluetooth';E('pStart').style.display='none';E('pStop').style.display='inline-block'}\n"
  "else if(d.paired){E('pBadge').className='pair-status badge-ok';E('pBadge').innerHTML='Paired';E('pInfo').innerHTML='Connected: <b>'+d.name+'</b> ('+d.mac+')';E('pStart').style.display='inline-block';E('pStop').style.display='none'}\n"
  "else{E('pBadge').className='pair-status badge-none';E('pBadge').innerHTML='None';E('pInfo').innerHTML='Tap start and search on phone';E('pStart').style.display='inline-block';E('pStop').style.display='none'}}).catch(function(){})}\n"
  "\n"
  "function openSettings(){E('settingsOverlay').style.display='flex';fetch('/api/status').then(function(r){return r.json()}).then(function(d){\n"
  "if(E('cfgSsid'))E('cfgSsid').value=d.wifi_ssid||'';if(E('cfgBt'))E('cfgBt').value=d.bt_name||'';if(E('cfgSec'))E('cfgSec').checked=d.sec_auth||false;\n"
  "if(E('cfgBleScan'))E('cfgBleScan').checked=d.ble_scan===true;if(E('cfgNfcScan'))E('cfgNfcScan').checked=d.nfc_scan||false}).catch(function(){})}\n"
  "function closeSettings(){E('settingsOverlay').style.display='none'}\n"
  "function saveSettings(){var u='/api/update_config?new_ssid='+encodeURIComponent(E('cfgSsid').value)+'&new_bt='+encodeURIComponent(E('cfgBt').value);if(E('cfgPass').value)u+='&new_pass='+encodeURIComponent(E('cfgPass').value);if(E('cfgPwd').value)u+='&new_pwd='+encodeURIComponent(E('cfgPwd').value);u+='&sec_auth='+E('cfgSec').checked+'&ble_scan='+E('cfgBleScan').checked+'&nfc_scan='+E('cfgNfcScan').checked;fetch(u,{method:'POST'}).then(function(r){if(r.status===200){addLog('Settings saved','ok');toast('Settings saved','ok');closeSettings()}else{E('settingsMsg').innerHTML='Save failed: '+r.status}}).catch(function(){E('settingsMsg').innerHTML='Network error'})}\n"
  "function rebootDevice(){if(confirm('Reboot device?')){fetch('/api/reboot');setTimeout(function(){location.reload()},5000)}}\n"
  "\n"
  "function startPair(){fetch('/api/ble/pairing/start').then(function(r){return r.json()}).then(function(d){addLog(d.message,'ok');updatePairStatus()}).catch(function(){addLog('Pair start failed','err')})}\n"
  "function stopPair(){fetch('/api/ble/pairing/stop').then(function(r){return r.json()}).then(function(d){addLog(d.message,'ok');updatePairStatus()}).catch(function(){addLog('Pair stop failed','err')})}\n"
  "function clearPair(){if(!confirm('Clear pairing info?'))return;fetch('/api/ble/pairing/clear').then(function(r){return r.json()}).then(function(d){addLog(d.message,'ok');updatePairStatus()}).catch(function(){addLog('Clear failed','err')})}\n"
  "\n"
  "function startOtaUpload(){E('otaFileInput').click()}\n"
  "function handleOtaFile(){var f=E('otaFileInput').files[0];if(!f)return;if(!f.name.endsWith('.bin')){addLog('Please select .bin file','err');return}if(!confirm('Upload '+f.name+' ('+(f.size/1024).toFixed(1)+'KB) and upgrade?'))return;addLog('Uploading: '+f.name,'info');E('otaProgressWrap').style.display='block';E('otaUploadBtn').disabled=true;var xhr=new XMLHttpRequest();xhr.upload.onprogress=function(e){if(e.lengthComputable){var pct=Math.round(e.loaded/e.total*100);E('otaProgressFill').style.width=pct+'%';E('otaProgressText').innerHTML=pct+'% ('+(e.loaded/1024).toFixed(0)+'/'+(e.total/1024).toFixed(0)+'KB)'}};xhr.onload=function(){if(xhr.status===200){addLog('Upload OK, rebooting...','ok');toast('OTA Upgrade OK','ok');E('otaProgressText').innerHTML='Upgrading, rebooting...';setTimeout(function(){location.reload()},5000)}else{addLog('Upload failed: '+xhr.status,'err');E('otaProgressWrap').style.display='none';E('otaUploadBtn').disabled=false}};xhr.onerror=function(){addLog('Upload connection failed','err');E('otaProgressWrap').style.display='none';E('otaUploadBtn').disabled=false};xhr.open('POST','/api/ota',true);xhr.send(f)}\n"
  "function startOtaDownload(){var url=E('otaUrl').value.trim();if(!url){addLog('Enter firmware URL','err');return}if(!confirm('Download from '+url+' and upgrade?'))return;addLog('Downloading firmware...','info');fetch('/api/ota/download',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'url='+encodeURIComponent(url)}).then(function(r){return r.text()}).then(function(t){addLog('Result: '+t,'ok');if(t.indexOf('success')!==-1||t.indexOf('started')!==-1){addLog('Rebooting...','ok');setTimeout(function(){location.reload()},5000)}}).catch(function(){addLog('Download failed','err')})}\n"
  "function doRollback(){if(!confirm('Rollback to previous version?'))return;fetch('/api/ota/rollback').then(function(r){return r.json()}).then(function(d){if(d.success){addLog('Rollback OK, rebooting...','ok');setTimeout(function(){location.reload()},5000)}else{addLog('Rollback failed: '+d.message,'err')}}).catch(function(){addLog('Rollback failed','err')})}\n"
  "function updateOtaInfo(){fetch('/api/ota/status').then(function(r){return r.json()}).then(function(d){var v=d.version||('Partition:'+d.partition);E('otaVer').innerHTML='Version: '+v;E('otaRollbackBtn').style.display=d.stored_fw?'inline-block':'none'}).catch(function(){})}\n"
  "\n"
  "function fetchServerLogs(){fetch('/api/logs').then(function(r){return r.text()}).then(function(t){if(!t)return;var lines=t.split('\\n');for(var i=0;i<lines.length;i++){var line=lines[i];if(!line)continue;var p=line.indexOf('|');if(p===-1){addLog(line,'info');continue}addLog(line.substring(p+1),line.substring(0,p))}}).catch(function(){})}\n"
  "\n"
  "connectWS();renderVehicleSvg(false,0,'--',false,false,false);updatePairStatus();updateOtaInfo();\n"
  "setInterval(function(){if(!_wsConnected)connectWS()},10000);\n"
  "setInterval(updateStatus,2000);setInterval(updatePairStatus,3000);\n"
  "setInterval(fetchServerLogs,2000);setInterval(updateOtaInfo,10000);\n"
  "</script>\n"
  "</body>\n"
  "</html>\n"
;
