#pragma once
#include <pgmspace.h>
const char kEmbeddedIndexPage[] PROGMEM =
  "<!DOCTYPE html>\n"
  "<html lang=\"zh\">\n"
  "<head>\n"
  "<meta charset=\"UTF-8\">\n"
  "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,user-scalable=no\">\n"
  "<title>CarKey V5</title>\n"
  "<style>\n"
  ":root{--bg:#060b14;--card:#0f1629;--txt:#e2e8f0;--sub:#64748b;--blue:#3b82f6;--green:#10b981;--red:#ef4444;--amber:#f59e0b;--border:rgba(255,255,255,0.06);--glow:rgba(59,130,246,0.25)}\n"
  "*{box-sizing:border-box;-webkit-tap-highlight-color:transparent;outline:none;margin:0}\n"
  "body{font-family:'Segoe UI',system-ui,sans-serif;background:var(--bg);color:var(--txt);padding:12px;min-height:100vh;max-width:480px;margin:0 auto}\n"
  ".header{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;padding:8px 0}\n"
  ".logo{display:flex;align-items:center;gap:8px}\n"
  ".logo-icon{width:36px;height:36px;border-radius:10px;background:linear-gradient(135deg,var(--blue),#2563eb);display:flex;align-items:center;justify-content:center;font-size:20px;box-shadow:0 0 16px var(--glow)}\n"
  ".logo-text{font-size:16px;font-weight:700;letter-spacing:2px}\n"
  ".logo-text span{font-weight:300;color:var(--sub);font-size:12px;letter-spacing:1px}\n"
  ".nav-btn{font-size:22px;cursor:pointer;color:var(--sub);padding:6px;transition:0.2s}\n"
  ".nav-btn:active{color:var(--blue);transform:scale(0.9)}\n"
  ".status-bar{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:12px}\n"
  ".status-chip{display:flex;align-items:center;gap:4px;background:var(--card);border:1px solid var(--border);border-radius:8px;padding:6px 10px;font-size:10px;color:var(--sub);white-space:nowrap}\n"
  ".status-chip .icon{font-size:13px}\n"
  ".status-chip .val{font-weight:600;color:var(--txt);margin-left:2px}\n"
  ".status-chip.on .val{color:var(--green)}\n"
  ".status-chip.off .val{color:var(--sub)}\n"
  ".status-chip.warn .val{color:var(--amber)}\n"
  ".engine-section{display:flex;justify-content:center;margin:18px 0 14px}\n"
  ".engine-btn{width:130px;height:130px;border-radius:50%;background:linear-gradient(145deg,#1a2540,#0d1525);border:2px solid rgba(59,130,246,0.4);box-shadow:0 0 40px var(--glow),inset 0 0 30px rgba(59,130,246,0.05);display:flex;flex-direction:column;align-items:center;justify-content:center;cursor:pointer;transition:all 0.3s;position:relative}\n"
  ".engine-btn::after{content:'';position:absolute;inset:-4px;border-radius:50%;border:1px solid rgba(59,130,246,0.15);animation:pulse-ring 2s infinite}\n"
  ".engine-btn:active{transform:scale(0.93);box-shadow:0 0 60px var(--glow)}\n"
  ".engine-btn .eng-icon{font-size:32px;margin-bottom:2px}\n"
  ".engine-btn .eng-title{font-size:13px;font-weight:700;letter-spacing:1px}\n"
  ".engine-btn .eng-sub{font-size:9px;color:var(--sub);margin-top:1px}\n"
  ".engine-btn.running{background:linear-gradient(145deg,#0f2d1a,#0d1525);border-color:rgba(16,185,129,0.5);box-shadow:0 0 40px rgba(16,185,129,0.3),inset 0 0 30px rgba(16,185,129,0.05)}\n"
  ".engine-btn.running::after{border-color:rgba(16,185,129,0.2)}\n"
  "@keyframes pulse-ring{0%,100%{opacity:0.5;transform:scale(1)}50%{opacity:1;transform:scale(1.06)}}\n"
  ".grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:14px}\n"
  ".act-card{display:flex;align-items:center;gap:10px;padding:14px 12px;cursor:pointer;background:var(--card);border:1px solid var(--border);border-radius:12px;transition:0.2s}\n"
  ".act-card:active{background:rgba(59,130,246,0.08);border-color:rgba(59,130,246,0.3)}\n"
  ".act-icon{font-size:24px;width:40px;text-align:center;flex-shrink:0}\n"
  ".act-info{display:flex;flex-direction:column}\n"
  ".act-title{font-size:12px;font-weight:600}\n"
  ".act-sub{font-size:10px;color:var(--sub);margin-top:1px}\n"
  ".vstat-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-bottom:12px}\n"
  ".vstat-card{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:10px 8px;display:flex;flex-direction:column;align-items:center;gap:4px;transition:0.3s}\n"
  ".vstat-card .vs-icon{font-size:18px}\n"
  ".vstat-card .vs-label{font-size:9px;color:var(--sub);letter-spacing:0.5px;text-transform:uppercase}\n"
  ".vstat-card .vs-val{font-size:13px;font-weight:700}\n"
  ".vstat-card .vs-sub{font-size:9px;color:var(--sub)}\n"
  ".vstat-card.on .vs-val{color:var(--green)}\n"
  ".vstat-card.off .vs-val{color:var(--red)}\n"
  ".vstat-card.warn .vs-val{color:var(--amber)}\n"
  ".vstat-card .vs-icon.good{color:var(--green)}\n"
  ".vstat-card .vs-icon.low{color:var(--amber)}\n"
  ".vstat-card .vs-icon.crit{color:var(--red)}\n"
  ".vstat-batt{grid-column:span 2}\n"
  ".card{background:var(--card);border-radius:12px;padding:12px 14px;margin-bottom:12px;border:1px solid var(--border)}\n"
  ".pair-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:6px}\n"
  ".pair-label{font-size:11px;color:var(--blue);letter-spacing:1px;font-weight:600}\n"
  ".pair-badge{font-size:9px;padding:2px 8px;border-radius:10px;font-weight:500}\n"
  ".badge-none{background:rgba(100,116,139,0.15);color:var(--sub)}\n"
  ".badge-ok{background:rgba(16,185,129,0.15);color:var(--green)}\n"
  ".badge-ing{background:rgba(59,130,246,0.15);color:var(--blue);animation:pulse 1.5s infinite}\n"
  "@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.5}}\n"
  ".pair-info{font-size:10px;color:var(--sub);margin:4px 0}\n"
  ".pair-actions{display:flex;gap:6px;margin-top:6px}\n"
  ".pair-btn{font-size:10px;padding:5px 12px;border-radius:6px;border:1px solid var(--border);background:transparent;color:var(--sub);cursor:pointer;transition:0.2s}\n"
  ".pair-btn:active{background:rgba(59,130,246,0.15);color:var(--blue)}\n"
  ".pair-btn.danger:active{background:rgba(239,68,68,0.15);color:var(--red)}\n"
  ".log-header{font-size:11px;color:var(--sub);margin-bottom:6px;font-weight:600}\n"
  ".log-list{display:flex;flex-direction:column;gap:3px;max-height:160px;overflow-y:auto}\n"
  ".log-item{background:rgba(0,0,0,0.3);padding:4px 8px;border-radius:5px;font-size:9px;display:flex;gap:6px}\n"
  ".log-time{color:var(--sub);white-space:nowrap;flex-shrink:0}\n"
  ".footer{text-align:center;font-size:9px;color:var(--sub);margin-top:16px;padding:8px 0}\n"
  ".overlay{position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(6,11,20,0.96);display:none;justify-content:center;align-items:center;z-index:9999}\n"
  ".modal-box{background:var(--card);border:1px solid rgba(59,130,246,0.2);border-radius:14px;padding:20px;width:90%;max-width:360px}\n"
  ".modal-title{font-size:14px;font-weight:600;margin-bottom:14px;display:flex;align-items:center;gap:8px}\n"
  ".btn-row{display:flex;gap:8px;margin-top:14px;justify-content:flex-end}\n"
  ".btn{padding:8px 16px;border-radius:8px;border:none;cursor:pointer;font-size:12px;font-weight:500;transition:0.2s}\n"
  ".btn-primary{background:var(--blue);color:#fff}\n"
  ".btn-danger{background:var(--red);color:#fff}\n"
  ".btn-ghost{background:transparent;border:1px solid var(--border);color:var(--sub)}\n"
  "label{display:block;font-size:11px;color:var(--sub);margin:10px 0 3px}\n"
  "input,select{width:100%;padding:8px 10px;border-radius:8px;border:1px solid var(--border);background:rgba(0,0,0,0.3);color:var(--txt);font-size:13px}\n"
  ".toggle-row{display:flex;justify-content:space-between;align-items:center;padding:5px 0;font-size:11px}\n"
  ".toggle{position:relative;display:inline-block;width:42px;height:24px}\n"
  ".toggle input{display:none}\n"
  ".toggle .slider{position:absolute;cursor:pointer;top:0;left:0;right:0;bottom:0;background:rgba(100,116,139,0.3);border-radius:24px;transition:0.3s}\n"
  ".toggle .slider::before{content:'';position:absolute;height:18px;width:18px;left:3px;bottom:3px;background:#fff;border-radius:50%;transition:0.3s}\n"
  ".toggle input:checked+.slider{background:var(--blue)}\n"
  ".toggle input:checked+.slider::before{transform:translateX(18px)}\n"
  ".ota-section{margin-top:8px;border-top:1px solid var(--border);padding-top:10px}\n"
".ota-title{font-size:11px;color:var(--blue);font-weight:600;margin-bottom:6px}\n"
".ota-ver{font-size:9px;color:var(--sub);margin-bottom:8px}\n"
".ota-row{display:flex;gap:6px;align-items:center;margin-bottom:6px;flex-wrap:wrap}\n"
".ota-input{flex:1;min-width:120px;padding:6px 8px;border-radius:6px;border:1px solid var(--border);background:rgba(0,0,0,0.3);color:var(--txt);font-size:10px}\n"
".ota-btn{font-size:10px;padding:5px 10px;border-radius:6px;border:1px solid var(--border);background:transparent;color:var(--sub);cursor:pointer;white-space:nowrap;transition:0.2s}\n"
".ota-btn:active{background:rgba(59,130,246,0.15);color:var(--blue)}\n"
".ota-btn.primary{background:var(--blue);color:#fff;border-color:var(--blue)}\n"
".ota-btn.danger{color:var(--red);border-color:var(--red)}\n"
".ota-btn.danger:active{background:rgba(239,68,68,0.15)}\n"
".ota-progress-wrap{display:none;margin:6px 0}\n"
".ota-progress-bar{width:100%;height:8px;border-radius:4px;background:rgba(255,255,255,0.08);overflow:hidden}\n"
".ota-progress-fill{height:100%;width:0%;background:linear-gradient(90deg,var(--blue),#2563eb);transition:width 0.3s;border-radius:4px}\n"
".ota-progress-text{font-size:9px;color:var(--sub);margin-top:3px;text-align:center}\n"
".divider{height:1px;background:var(--border);margin:8px 0}\n"
"</style>\n"
  "</head>\n"
  "<body>\n"
  "<div class=\"header\">\n"
  "  <div class=\"logo\">\n"
  "    <div class=\"logo-icon\">CK</div>\n"
  "    <div class=\"logo-text\">CARKEY <span>V5</span></div>\n"
  "  </div>\n"
  "  <span class=\"nav-btn\" onclick=\"openSettings()\" >&#9881;</span>\n"
  "</div>\n"
  "<div class=\"status-bar\" id=\"statusBar\">\n"
  "  <div class=\"status-chip\" id=\"chipGear\"><span class=\"icon\">&#9881;</span>&#25377;&#20301;<span class=\"val\">--</span></div>\n"
  "  <div class=\"status-chip\" id=\"chipBrake\"><span class=\"icon\">P</span>&#25163;&#21049;<span class=\"val\">--</span></div>\n"
  "  <div class=\"status-chip\" id=\"chipBle\"><span class=\"icon\">BT</span>&#34013;&#29273;<span class=\"val\">--</span></div>\n"
  "  <div class=\"status-chip\" id=\"chipNfc\"><span class=\"icon\">NF</span>NFC<span class=\"val\">--</span></div>\n"
  "  <div class=\"status-chip\" id=\"chipBatt\"><span class=\"icon\">BT</span><span class=\"val\">--.-V</span></div>\n"
  "</div>\n"
  "<div class=\"engine-section\">\n"
  "  <div class=\"engine-btn\" id=\"engBtn\" onclick=\"toggleEngine()\" >\n"
  "    <div class=\"eng-icon\">&#9889;</div>\n"
  "    <div class=\"eng-title\" id=\"engTitle\">START</div>\n"
  "    <div class=\"eng-sub\" id=\"engSub\">&#28857;&#20987;&#21551;&#21160;</div>\n"
  "  </div>\n"
  "</div>\n"
  "<!-- V1.1 Vehicle Status Cards -->\n"
  "<div class=\"vstat-grid\">\n"
  "  <div class=\"vstat-card off\" id=\"cardEngine\">\n"
  "    <div class=\"vs-icon\">&#9889;</div>\n"
  "    <div class=\"vs-label\">ENGINE</div>\n"
  "    <div class=\"vs-val\" id=\"vEngine\">STOPPED</div>\n"
  "  </div>\n"
  "  <div class=\"vstat-card\" id=\"cardBatt\">\n"
  "    <div class=\"vs-icon good\" id=\"vBattIcon\">&#9889;</div>\n"
  "    <div class=\"vs-label\">BATTERY</div>\n"
  "    <div class=\"vs-val\" id=\"vBattV\">--.-V</div>\n"
  "    <div class=\"vs-sub\" id=\"vBattH\">--</div>\n"
  "  </div>\n"
  "  <div class=\"vstat-card off\" id=\"cardAcc\">\n"
  "    <div class=\"vs-icon\">&#128268;</div>\n"
  "    <div class=\"vs-label\">ACC</div>\n"
  "    <div class=\"vs-val\" id=\"vAcc\">OFF</div>\n"
  "  </div>\n"
  "  <div class=\"vstat-card off\" id=\"cardBrake\">\n"
  "    <div class=\"vs-icon\">&#9888;</div>\n"
  "    <div class=\"vs-label\">PARK BRAKE</div>\n"
  "    <div class=\"vs-val\" id=\"vBrake\">RELEASED</div>\n"
  "  </div>\n"
  "  <div class=\"vstat-card off\" id=\"cardDoor\">\n"
  "    <div class=\"vs-icon\">&#128682;</div>\n"
  "    <div class=\"vs-label\">DOOR</div>\n"
  "    <div class=\"vs-val\" id=\"vDoor\">CLOSED</div>\n"
  "  </div>\n"
  "</div>\n"
  "<div class=\"grid\">\n"
  "  <div class=\"act-card\" onclick='doApi(\"/api/unlock\")'>\n"
  "    <div class=\"act-icon\">&#128275;</div>\n"
  "    <div class=\"act-info\"><div class=\"act-title\">&#35299;&#38145;</div><div class=\"act-sub\">&#36710;&#38376;&#35299;&#38145;</div></div>\n"
  "  </div>\n"
  "  <div class=\"act-card\" onclick='doApi(\"/api/lock\")'>\n"
  "    <div class=\"act-icon\">&#128274;</div>\n"
  "    <div class=\"act-info\"><div class=\"act-title\">&#19978;&#38145;</div><div class=\"act-sub\">&#36710;&#38376;&#19978;&#38145;</div></div>\n"
  "  </div>\n"
  "  <div class=\"act-card\" onclick='doApi(\"/api/horn\")'>\n"
  "    <div class=\"act-icon\">&#128226;</div>\n"
  "    <div class=\"act-info\"><div class=\"act-title\">&#40483;&#31523;</div><div class=\"act-sub\">&#23547;&#36710;&#40483;&#31523;</div></div>\n"
  "  </div>\n"
  "  <div class=\"act-card\" onclick='doApi(\"/api/window\")'>\n"
  "    <div class=\"act-icon\">&#9644;</div>\n"
  "    <div class=\"act-info\"><div class=\"act-title\">&#36710;&#31383;</div><div class=\"act-sub\">&#21319;&#38477;&#36710;&#31383;</div></div>\n"
  "  </div>\n"
  "</div>\n"
  "\n"
  "<div class=\"card\">\n"
  "  <div class=\"log-header\">&#128203; &#25805;&#20316;&#26085;&#24535;</div>\n"
  "  <div class=\"log-list\" id=\"logList\"></div>\n"
  "</div>\n"
  "<div class=\"footer\">CarKey V5 &copy; 2025</div>\n"
  "<div class=\"overlay\" id=\"authOverlay\">\n"
  "  <div class=\"modal-box\">\n"
  "    <div class=\"modal-title\" id=\"authModalTitle\">&#128272; &#21551;&#21160;&#39564;&#35777;</div>\n"
  "    <label>&#35831;&#36755;&#20837;&#21551;&#21160;&#23494;&#30721;</label>\n"
  "    <input type=\"password\" id=\"authPwd\" placeholder=\"6&#20301;&#25968;&#23383;&#23494;&#30721;\" maxlength=\"6\" inputmode=\"numeric\" autocomplete=\"off\">\n"
  "    <div id=\"authMsg\" style=\"font-size:11px;color:var(--red);margin-top:6px\"></div>\n"
  "    <div class=\"btn-row\">\n"
  "      <button class=\"btn btn-ghost\" onclick=\"closeAuth()\" >&#21462;&#28040;</button>\n"
  "      <button class=\"btn btn-primary\" onclick=\"doStart()\" >&#21551;&#21160;&#24341;&#25806;</button>\n"
  "    </div>\n"
  "  </div>\n"
  "</div>\n"
  "<div class=\"overlay\" id=\"settingsOverlay\">\n"
  "  <div class=\"modal-box\">\n"
  "    <div class=\"modal-title\">&#9881; &#31995;&#32479;&#35774;&#32622;</div>\n"
  "    <label>WiFi SSID</label>\n"
  "    <input type=\"text\" id=\"cfgSsid\" placeholder=\"WiFi&#21517;&#31216;\">\n"
  "    <label>WiFi &#23494;&#30721;</label>\n"
  "    <input type=\"password\" id=\"cfgPass\" placeholder=\"WiFi&#23494;&#30721;\">\n"
  "    <label>&#34013;&#29273;&#21517;&#31216;</label>\n"
  "    <input type=\"text\" id=\"cfgBt\" placeholder=\"&#34013;&#29273;&#35774;&#22791;&#21517;\">\n"
  "    <label>&#21551;&#21160;&#23494;&#30721;</label>\n"
  "    <input type=\"password\" id=\"cfgPwd\" placeholder=\"6&#20301;&#26032;&#21551;&#21160;&#23494;&#30721;\">\n"
  "    <div class=\"toggle-row\">\n"
  "      <span>&#23433;&#20840;&#35748;&#35777;</span>\n"
  "      <label class=\"toggle\"><input type=\"checkbox\" id=\"cfgSec\"><span class=\"slider\"></span></label>\n"
  "    </div>\n"
  "    <div class=\"toggle-row\">\n"
  "      <span>BLE&#25195;&#25551;</span>\n"
  "      <label class=\"toggle\"><input type=\"checkbox\" id=\"cfgBleScan\"><span class=\"slider\"></span></label>\n"
  "    </div>\n"
  "    <div class=\"toggle-row\">\n"
  "      <span>NFC&#25195;&#25551;</span>\n"
  "      <label class=\"toggle\"><input type=\"checkbox\" id=\"cfgNfcScan\"><span class=\"slider\"></span></label>\n"
  "    </div>\n"
  "    <div class=\"divider\"></div>\n"
  "    <div style=\"font-size:11px;color:var(--blue);font-weight:600;margin-bottom:6px\">&#128225; BLE &#37197;&#23545;</div>\n"
  "    <div id=\"pInfo\" style=\"font-size:10px;color:var(--sub);margin:4px 0\">&#28857;&#20987;&#24320;&#22987;&#37197;&#23545;&#65292;&#22312;&#25163;&#26426;&#34013;&#29273;&#20013;&#25628;&#32032;&#35774;&#22791;</div>\n"
  "    <div style=\"display:flex;gap:6px;align-items:center\">\n"
  "      <button class=\"btn-sm\" id=\"pStart\" onclick=\"startPair()\">&#24320;&#22987;&#37197;&#23545;</button>\n"
  "      <button class=\"btn-sm\" id=\"pStop\" onclick=\"stopPair()\" style=\"display:none\">&#20572;&#27490;</button>\n"
  "      <button class=\"btn-sm danger\" onclick=\"clearPair()\">&#28165;&#38500;</button>\n"
  "      <span class=\"pair-status badge-none\" id=\"pBadge\">&#26410;&#37197;&#23545;</span>\n"
  "    </div>\n"
  "    <div class=\"divider\"></div>\n"
  "    <div class=\"ota-section\">\n"
  "      <div class=\"ota-title\">&#128190; OTA &#22266;&#20214;&#21319;&#32423;</div>\n"
  "      <div class=\"ota-ver\" id=\"otaVer\">&#24403;&#21069;&#29256;&#26412;: --</div>\n"
  "      <div class=\"ota-row\">\n"
  "        <button class=\"ota-btn primary\" id=\"otaUploadBtn\" onclick=\"startOtaUpload()\">&#36873;&#25321;&#25991;&#20214;&#21319;&#32423;</button>\n"
  "        <input type=\"file\" id=\"otaFileInput\" accept=\".bin\" style=\"display:none\" onchange=\"handleOtaFile()\">\n"
  "      </div>\n"
  "      <div class=\"ota-row\">\n"
  "        <input type=\"text\" class=\"ota-input\" id=\"otaUrl\" placeholder=\"&#25110;&#36755;&#20837;&#22266;&#20214;URL&#19979;&#36733;...\">\n"
  "        <button class=\"ota-btn\" onclick=\"startOtaDownload()\">&#19979;&#36733;</button>\n"
  "      </div>\n"
  "      <div class=\"ota-progress-wrap\" id=\"otaProgressWrap\">\n"
  "        <div class=\"ota-progress-bar\"><div class=\"ota-progress-fill\" id=\"otaProgressFill\"></div></div>\n"
  "        <div class=\"ota-progress-text\" id=\"otaProgressText\">0%</div>\n"
  "      </div>\n"
  "      <div class=\"ota-row\">\n"
  "        <button class=\"ota-btn danger\" id=\"otaRollbackBtn\" style=\"display:none\" onclick=\"doRollback()\">&#22238;&#28378;&#19978;&#19968;&#29256;</button>\n"
  "      </div>\n"
  "    </div>\n"
  "    <div class=\"divider\"></div>\n"
  "    <div class=\"btn-row\">\n"
  "      <button class=\"btn btn-ghost\" onclick=\"closeSettings()\" >&#21462;&#28040;</button>\n"
  "      <button class=\"btn btn-danger\" onclick=\"rebootDevice()\" >&#37325;&#21551;</button>\n"
  "      <button class=\"btn btn-primary\" onclick=\"saveSettings()\" >&#20445;&#23384;</button>\n"
  "    </div>\n"
  "    <div id=\"settingsMsg\" style=\"font-size:11px;color:var(--red);margin-top:8px\"></div>\n"
  "  </div>\n"
  "</div>\n"
  "<script>\n"
  "var E=function(id){return document.getElementById(id)};\n"
  "function addLog(m,t){\n"
  "  var l=E('logList');if(!l)return;\n"
  "  var d=new Date(),ts=('0'+d.getHours()).slice(-2)+':'+('0'+d.getMinutes()).slice(-2)+':'+('0'+d.getSeconds()).slice(-2);\n"
  "  var c=t==='err'?'var(--red)':t==='ok'?'var(--green)':'var(--sub)';\n"
  "  l.innerHTML='<div class=\"log-item\"><span class=\"log-time\">'+ts+'</span><span style=\"color:'+c+'\">'+m+'</span></div>'+l.innerHTML;\n"
  "  if(l.children.length>50)l.removeChild(l.lastChild);\n"
  "}\n"
  "function toggleEngine(){var rn=E('engBtn').classList.contains('running');if(rn){if(confirm('\\u786E\\u5B9A\\u505C\\u6B62\\u5F15\\u64CE?')){openAuth('stop')}}else{openAuth('start')}}\n"
  "function openAuth(m){window._authMode=m||'start';E('authOverlay').style.display='flex';E('authPwd').focus();var t=m==='stop'?'\\u505C\\u6B62\\u9A8C\\u8BC1':'\\u542F\\u52A8\\u9A8C\\u8BC1';E('authModalTitle').innerHTML=t;var b=m==='stop'?'\\u505C\\u6B62\\u5F15\\u64CE':'\\u542F\\u52A8\\u5F15\\u64CE';E('authSubmitBtn').innerHTML=b}\n"
  "function closeAuth(){E('authOverlay').style.display='none';E('authPwd').value='';E('authMsg').innerHTML=''}\n"
  "function doStart(){\n"
  "  var p=E('authPwd').value;\n"
  "  if(!p||p.length!==6){E('authMsg').innerHTML='\\u8BF7\\u8F93\\u51656\\u4F4D\\u5BC6\\u7801';return}\n"
  "  var mode=window._authMode||'start';\n"
  "  var url=mode==='stop'?'/api/stop_engine?pwd='+p:'/api/start_engine?pwd='+p;\n"
  "  var label=mode==='stop'?'\\u505C\\u6B62\\u5F15\\u64CE':'\\u542F\\u52A8\\u5F15\\u64CE';\n"
  "  addLog(label+'...','info');\n"
  "  fetch(url).then(function(r){\n"
  "    if(r.status===200||r.status===202){addLog(label+'\\u6210\\u529F','ok');closeAuth();return}\n"
  "    return r.text().then(function(t){if(r.status===401)E('authMsg').innerHTML='\\u5BC6\\u7801\\u9519\\u8BEF';else if(r.status===409)E('authMsg').innerHTML='\\u5F15\\u64CE\\u672A\\u8FD0\\u884C';else E('authMsg').innerHTML=t})\n"
  "  }).catch(function(){addLog('\\u7F51\\u7EDC\\u9519\\u8BEF','err')});\n"
  "}\n"
  "function doApi(url){addLog('\\u6267\\u884C: '+url,'info');fetch(url).then(function(r){return r.text()}).then(function(t){addLog('\\u6210\\u529F: '+t,'ok')}).catch(function(){addLog('\\u5931\\u8D25','err')});}\n"
  "function openSettings(){\n"
  "  E('settingsOverlay').style.display='flex';\n"
  "  fetch('/api/status').then(function(r){return r.json()}).then(function(d){\n"
  "    if(E('cfgSsid'))E('cfgSsid').value=d.wifi_ssid||'';\n"
  "    if(E('cfgBt'))E('cfgBt').value=d.bt_name||'';\n"
  "    if(E('cfgSec'))E('cfgSec').checked=d.sec_auth||false;\n"
  "    if(E('cfgBleScan'))E('cfgBleScan').checked=d.ble_scan===true;\n"
  "    if(E('cfgNfcScan'))E('cfgNfcScan').checked=d.nfc_scan||false;\n"
  "  }).catch(function(){});\n"
  "}\n"
  "function closeSettings(){E('settingsOverlay').style.display='none'}\n"
  "function saveSettings(){\n"
  "  var u='/api/update_config?new_ssid='+encodeURIComponent(E('cfgSsid').value)+'&new_bt='+encodeURIComponent(E('cfgBt').value);\n"
  "  if(E('cfgPass').value)u+='&new_pass='+encodeURIComponent(E('cfgPass').value);\n"
  "  if(E('cfgPwd').value)u+='&new_pwd='+encodeURIComponent(E('cfgPwd').value);\n"
  "  u+='&sec_auth='+E('cfgSec').checked+'&ble_scan='+E('cfgBleScan').checked+'&nfc_scan='+E('cfgNfcScan').checked;\n"
  "  fetch(u,{method:'POST'}).then(function(r){\n"
  "    if(r.status===200){addLog('\\u4FDD\\u5B58\\u6210\\u529F','ok');closeSettings()}\n"
  "    else{addLog('\\u4FDD\\u5B58\\u5931\\u8D25: '+r.status,'err')}\n"
  "  }).catch(function(){addLog('\\u7F51\\u7EDC\\u9519\\u8BEF','err')});\n"
  "}\n"
  "function rebootDevice(){if(confirm('\\u786E\\u5B9A\\u91CD\\u542F\\u8BBE\\u5907?')){fetch('/api/reboot');setTimeout(function(){location.reload()},3000)}}\n"
  "var _lastEngine=null;var _lastLocked=null;\n"
  "function updateStatus(){\n"
  "  fetch('/api/status').then(function(r){return r.json()}).then(function(d){\n"
  "    var rn=d.engine_running;\n"
  "    if(_lastEngine!==null&&_lastEngine!==rn){addLog(rn?'\\u5F15\\u64CE\\u5DF2\\u542F\\u52A8':'\\u5F15\\u64CE\\u5DF2\\u505C\\u6B62',rn?'ok':'info')}\n"
  "    _lastEngine=rn;\n"
  "    var cl=d.config_locked;\n"
  "    if(_lastLocked!==null&&_lastLocked!==cl){addLog(cl?'NFC\\u5DF2\\u9501\\u5B9A\\u914D\\u7F6E':'NFC\\u5DF2\\u89E3\\u9501',cl?'warn':'ok')}\n"
  "    _lastLocked=cl;\n"
  "    var btn=E('engBtn');\n"
  "    E('engTitle').innerHTML=rn?'STOP':'START';\n"
  "    E('engSub').innerHTML=rn?'\\u5F15\\u64CE\\u8FD0\\u884C\\u4E2D':'\\u70B9\\u51FB\\u542F\\u52A8\\u5F15\\u64CE';\n"
  "    if(rn){btn.classList.add('running')}else{btn.classList.remove('running')}\n"
  "    E('engTitle').style.color=rn?'var(--green)':'';\n"
  "    var v=d.voltage||0;\n"
  "    E('chipBatt').querySelector('.val').innerHTML=v?v.toFixed(1)+' V':'--.-V';\n"
  "    var g=d.gear||'--';\n"
  "    var gc=E('chipGear');gc.querySelector('.val').innerHTML=g;\n"
  "    gc.className='status-chip'+(g==='N'?' on':'');\n"
  "    var hb=d.handbrake;\n"
  "    var bc=E('chipBrake');bc.querySelector('.val').innerHTML=hb?'\\u5DF2\\u62C9\\u8D77':'\\u5DF2\\u91CA\\u653E';\n"
  "    bc.className='status-chip'+(hb?' on':' off');\n"
  "    var blc=E('chipBle');\n"
  "    if(d.ble_scan===false){\n"
  "      blc.querySelector('.val').innerHTML='\\u5DF2\\u5173\\u95ED';\n"
  "      blc.className='status-chip off';\n"
  "    }else if(d.ble_authorized||d.ble_auth_valid){\n"
  "      blc.querySelector('.val').innerHTML='\\u5DF2\\u8BA4\\u8BC1';\n"
  "      blc.className='status-chip on';\n"
  "    }else if(d.ble_scanning){\n"
  "      blc.querySelector('.val').innerHTML='\\u626B\\u63CF\\u4E2D';\n"
  "      blc.className='status-chip on';\n"
  "    }else if(d.ble_last_seen>0){\n"
  "      blc.querySelector('.val').innerHTML=d.ble_last_seen+'s\\u524D';\n"
  "      blc.className='status-chip off';\n"
  "    }else{\n"
  "      blc.querySelector('.val').innerHTML='\\u5F85\\u673A';\n"
  "      blc.className='status-chip off';\n"
  "    }\n"
  "    var cl=d.config_locked;\n"
  "    var nc=E('chipNfc');\n"
  "    if(d.nfc_scan===false){\n"
  "      nc.querySelector('.val').innerHTML='\\u5DF2\\u5173\\u95ED';\n"
  "      nc.className='status-chip off';\n"
  "    }else if(d.config_locked){     nc.querySelector('.val').innerHTML='\\u5DF2\\u9501\\u5B9A';\n"
  "      nc.className='status-chip warn';\n"
  "    }else{\n"
  "      nc.querySelector('.val').innerHTML='\\u5DF2\\u89E3\\u9501';\n"
  "      nc.className='status-chip on';\n"
  "    }\n"
  "    // V1.1: Update vehicle status cards\n"
  "    var er=d.engineRunning;\n"
  "    var ce=E(\"cardEngine\");\n"
  "    E(\"vEngine\").innerHTML=er?\"RUNNING\":\"STOPPED\";\n"
  "    if(er){ce.className=\"vstat-card on\"}else{ce.className=\"vstat-card off\"}\n"
  "    var bv=d.batteryVoltage||0;\n"
  "    var bh=d.batteryHealth||\"--\";\n"
  "    E(\"vBattV\").innerHTML=bv?bv.toFixed(1)+\"V\":\"--.-V\";\n"
  "    E(\"vBattH\").innerHTML=bh;\n"
  "    var bi=E(\"vBattIcon\");\n"
  "    if(bh===\"GOOD\"){bi.className=\"vs-icon good\"}else if(bh===\"LOW\"){bi.className=\"vs-icon low\"}else{bi.className=\"vs-icon crit\"}\n"
  "    var ac=d.acc;\n"
  "    var ae=E(\"cardAcc\");\n"
  "    E(\"vAcc\").innerHTML=ac?\"ON\":\"OFF\";\n"
  "    if(ac){ae.className=\"vstat-card on\"}else{ae.className=\"vstat-card off\"}\n"
  "    var hb=d.handBrake!==undefined?d.handBrake:d.handbrake;\n"
  "    var be=E(\"cardBrake\");\n"
  "    E(\"vBrake\").innerHTML=hb?\"ENGAGED\":\"RELEASED\";\n"
  "    if(hb){be.className=\"vstat-card on\"}else{be.className=\"vstat-card off\"}\n"
  "    var do_=d.driverDoorOpen;\n"
  "    var de=E(\"cardDoor\");\n"
  "    E(\"vDoor\").innerHTML=do_?\"OPEN\":\"CLOSED\";\n"
  "    if(do_){de.className=\"vstat-card on\"}else{de.className=\"vstat-card off\"}\n"
  "  }).catch(function(){});\n"
  "}\n"
  "function updatePairStatus(){\n"
  "  fetch('/api/ble/pairing/status').then(function(r){return r.json()}).then(function(d){\n"
  "    if(d.pairing){\n"
  "      E('pBadge').className='pair-badge badge-ing';E('pBadge').innerHTML='\\u914D\\u5BF9\\u4E2D...';\n"
  "      E('pInfo').innerHTML='\\u8BF7\\u5728\\u624B\\u673A\\u84DD\\u7259\\u8BBE\\u7F6E\\u4E2D\\u641C\\u7D20\\u5E76\\u914D\\u5BF9';\n"
  "      E('pStart').style.display='none';E('pStop').style.display='inline-block';\n"
  "    }else if(d.paired){\n"
  "      E('pBadge').className='pair-badge badge-ok';E('pBadge').innerHTML='\\u5DF2\\u914D\\u5BF9';\n"
  "      E('pInfo').innerHTML='\\u5DF2\\u8FDE\\u63A5: <b>'+d.name+'</b> ('+d.mac+')';\n"
  "      E('pStart').style.display='inline-block';E('pStop').style.display='none';\n"
  "      \n"
  "    }else{\n"
  "      E('pBadge').className='pair-badge badge-none';E('pBadge').innerHTML='\\u672A\\u914D\\u5BF9';\n"
  "      E('pInfo').innerHTML='\\u70B9\\u51FB\\u5F00\\u59CB\\u914D\\u5BF9\\uFF0C\\u5728\\u624B\\u673A\\u84DD\\u7259\\u4E2D\\u641C\\u7D20\\u8BBE\\u5907';\n"
  "      E('pStart').style.display='inline-block';E('pStop').style.display='none';\n"
  "    }\n"
  "  }).catch(function(){});\n"
  "}\n"
  "function startPair(){\n"
  "  addLog('\\u5F00\\u59CB\\u914D\\u5BF9...','info');\n"
  "  fetch('/api/ble/pairing/start').then(function(r){return r.json()}).then(function(d){\n"
  "    addLog(d.message,'ok');updatePairStatus();\n"
  "  }).catch(function(){addLog('\\u914D\\u5BF9\\u5931\\u8D25','err')});\n"
  "}\n"
  "function stopPair(){\n"
  "  fetch('/api/ble/pairing/stop').then(function(r){return r.json()}).then(function(d){\n"
  "    addLog(d.message,'ok');updatePairStatus();\n"
  "  }).catch(function(){addLog('\\u505C\\u6B62\\u5931\\u8D25','err')});\n"
  "}\n"
  "function clearPair(){\n"
  "  if(!confirm('\\u786E\\u5B9A\\u6E05\\u9664\\u914D\\u5BF9\\u4FE1\\u606F?'))return;\n"
  "  fetch('/api/ble/pairing/clear').then(function(r){return r.json()}).then(function(d){\n"
  "    addLog(d.message,'ok');updatePairStatus();\n"
  "  }).catch(function(){addLog('\\u6E05\\u9664\\u5931\\u8D25','err')});\n"
  "}\n"
  "addLog('\\u7CFB\\u7EDF\\u5C31\\u7EEA','ok');\n"
  "updateStatus();\n"
  "updatePairStatus();\n"
  "setInterval(updateStatus,2000);\n"
  "setInterval(updatePairStatus,3000);\n"
  "function fetchServerLogs(){\n"
  "  fetch('/api/logs').then(function(r){return r.text()}).then(function(t){\n"
  "    if(!t)return;\n"
  "    var lines=t.split('\\n');\n"
  "    for(var i=0;i<lines.length;i++){\n"
  "      var line=lines[i];if(!line)continue;\n"
  "      var p=line.indexOf('|');\n"
  "      if(p===-1){addLog(line,'info');continue;}\n"
  "      addLog(line.substring(p+1),line.substring(0,p));\n"
  "    }\n"
  "  }).catch(function(){});\n"
  "}\n"
  "setInterval(fetchServerLogs,2000);\n"
  "function startOtaUpload(){\n"
  "  E('otaFileInput').click();\n"
  "}\n"
  "function handleOtaFile(){\n"
  "  var f=E('otaFileInput').files[0];\n"
  "  if(!f)return;\n"
  "  if(!f.name.endsWith('.bin')){addLog('&#35831;&#36873;&#25321;.bin&#26684;&#24335;&#30340;&#22266;&#20214;&#25991;&#20214;','err');return;}\n"
  "  if(!confirm('&#30830;&#23450;&#19978;&#20256; '+f.name+' ('+(f.size/1024).toFixed(1)+'KB) &#24182;&#21319;&#32423;&#65311;'))return;\n"
  "  addLog('&#24320;&#22987;&#19978;&#20256;&#22266;&#20214;: '+f.name,'info');\n"
  "  E('otaProgressWrap').style.display='block';\n"
  "  E('otaUploadBtn').disabled=true;\n"
  "  var xhr=new XMLHttpRequest();\n"
  "  xhr.upload.onprogress=function(e){\n"
  "    if(e.lengthComputable){\n"
  "      var pct=Math.round(e.loaded/e.total*100);\n"
  "      E('otaProgressFill').style.width=pct+'%';\n"
  "      E('otaProgressText').innerHTML=pct+'% ('+(e.loaded/1024).toFixed(0)+'/'+(e.total/1024).toFixed(0)+'KB)';\n"
  "    }\n"
  "  };\n"
  "  xhr.onload=function(){\n"
  "    if(xhr.status===200){\n"
  "      addLog('&#22266;&#20214;&#19978;&#20256;&#25104;&#21151;&#65292;&#21363;&#23558;&#37325;&#21551;...','ok');\n"
  "      E('otaProgressText').innerHTML='&#21319;&#32423;&#25104;&#21151;&#65292;&#37325;&#21551;&#20013;...';\n"
  "      setTimeout(function(){location.reload()},5000);\n"
  "    }else{\n"
  "      addLog('&#19978;&#20256;&#22833;&#36133;: '+xhr.status,'err');\n"
  "      E('otaProgressWrap').style.display='none';\n"
  "      E('otaUploadBtn').disabled=false;\n"
  "    }\n"
  "  };\n"
  "  xhr.onerror=function(){\n"
  "    addLog('&#19978;&#20256;&#36830;&#25509;&#22833;&#36133;','err');\n"
  "    E('otaProgressWrap').style.display='none';\n"
  "    E('otaUploadBtn').disabled=false;\n"
  "  };\n"
  "  xhr.open('POST','/api/ota',true);\n"
  "  xhr.send(f);\n"
  "}\n"
  "function startOtaDownload(){\n"
  "  var url=E('otaUrl').value.trim();\n"
  "  if(!url){addLog('&#35831;&#36755;&#20837;&#22266;&#20214;&#19979;&#36733;URL','err');return;}\n"
  "  if(!confirm('&#30830;&#23450;&#20174; '+url+' &#19979;&#36733;&#24182;&#21319;&#32423;&#65311;'))return;\n"
  "  addLog('&#24320;&#22987;&#19979;&#36733;&#22266;&#20214;...','info');\n"
  "  fetch('/api/ota/download',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'url='+encodeURIComponent(url)})\n"
  "    .then(function(r){return r.text()})\n"
  "    .then(function(t){\n"
  "      addLog('&#19979;&#36733;&#32467;&#26524;: '+t,'ok');\n"
  "      if(t.indexOf('success')!==-1||t.indexOf('started')!==-1){\n"
  "        addLog('&#21319;&#32423;&#25104;&#21151;&#65292;&#21363;&#23558;&#37325;&#21551;...','ok');\n"
  "        setTimeout(function(){location.reload()},5000);\n"
  "      }\n"
  "    })\n"
  "    .catch(function(){addLog('&#19979;&#36733;&#22833;&#36133;','err')});\n"
  "}\n"
  "function doRollback(){\n"
  "  if(!confirm('&#30830;&#23450;&#22238;&#28378;&#21040;&#19978;&#19968;&#20010;&#29256;&#26412;&#65311;'))return;\n"
  "  fetch('/api/ota/rollback').then(function(r){return r.json()}).then(function(d){\n"
  "    if(d.success){addLog('&#22238;&#28378;&#25104;&#21151;&#65292;&#37325;&#21551;&#20013;...','ok');setTimeout(function(){location.reload()},5000)}\n"
  "    else{addLog('&#22238;&#28378;&#22833;&#36133;: '+d.message,'err')}\n"
  "  }).catch(function(){addLog('&#22238;&#28378;&#22833;&#36133;','err')});\n"
  "}\n"
  "function updateOtaInfo(){\n"
  "  fetch('/api/ota/status').then(function(r){return r.json()}).then(function(d){\n"
  "    var v=d.version||('&#20998;&#21306;:'+d.partition);\n"
  "    E('otaVer').innerHTML='&#24403;&#21069;&#29256;&#26412;: '+v;\n"
  "    E('otaRollbackBtn').style.display=d.stored_fw?'inline-block':'none';\n"
  "  }).catch(function(){});\n"
  "}\n"
  "updateOtaInfo();\n"
  "setInterval(updateOtaInfo,10000);\n"
  "</script>\n"
  "</body>\n"
  "</html>\n"
  "\n"
;
